# Config for SLURM jobs on cluster.

__default__:
  nodes: 1
  cpus-per-task: "{resources.cpus}"
  mem: "{resources.mem_mb}M"
  time: "02:00:00"
  output: "logs/slurm-%j.out"
  error: "logs/slurm-%j.err"
  partition: "cpu"
execution:
  mode: slurm
  jobs: 4
  cores: 1  # Local cores for the main Snakemake process
  latency_wait: 60
#  use_conda: true
  dry_run: false
  cluster_config: "config/cluster.yaml"  # Optional: SLURM-specific settings
trim_with_fastp:
  nodes: 1
  cpus-per-task: "{resources.cpus}"
  mem: "{resources.mem_mb}M"
  time: "04:00:00"
  partition: "cpu"