# Config for running CypherID locally.

input:
  base_dir: "data/input/"  # Same as default, but could be adjusted
output:
  base_dir: "data/output/"
logging:
  level: "INFO"           # More verbose for local debugging
  dir: "logs/"
resources:
  default:
    cpus: 4                # Limited to laptop’s cores
    mem_mb: 8000           # Limited to laptop’s RAM
execution:
  mode: local
  cores: 4
#  use_conda: true
  dry_run: false