# Config for running CypherID locally.

input:
  base_dir: "data/input/"  # Same as default, but could be adjusted
output:
  base_dir: "data/output/"
logging:
  level: "INFO"           # More verbose for local debugging
  dir: "logs/"
resources:
  default:
    cpus: 4
    mem_mb: 8000
execution:
  mode: local
  cores: 1
#  use_conda: true
  dry_run: false
trim_with_fastp:
  nodes: 1
  cpus-per-task: "{resources.cpus}"
  mem: "{resources.mem_mb}M"
  time: "04:00:00"
  partition: "cpu"