name: Snakemake Python Tests

# Trigger the workflow on pushes and pull requests to main and dev
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test_python:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Add this to allow OIDC token access
      contents: read   # Required for checkout
      checks: write    # For creating check runs (e.g., test-reporter)
    strategy:
      matrix:
        python-version: ['3.12', '3.13']  # Test across multiple Python versions

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::941377154785:role/GitHubActionsRole
          aws-region: us-west-2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Includes pytest, pytest-cov, etc.

      # Run pytest tests
      - name: Run pytest
        run: |
          python -m pytest
        env:
          PYTHONPATH: ${{ github.workspace }}  # Ensures scripts/ is importable

      # Publish test results
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()  # Runs even if tests fail
        with:
          name: Pytest Results (${{ matrix.python-version }})
          path: test-results.xml
          reporter: java-junit
